version: '3'
services:
    api:
        restart: on-failure
        build:
            context: ./
            dockerfile: Dockerfile
        volumes:
            - /app/node_modules
            - ./:/app
        ports:
            - '8000:8000'
